# Generated by Django 5.0.14 on 2026-02-28 21:06

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('session_key', models.CharField(blank=True, db_index=True, default='', help_text='Anonymous session identifier', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='WebPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(db_index=True, max_length=1024, unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=512)),
                ('content', models.TextField(help_text='Raw text content extracted from the page')),
                ('html', models.TextField(blank=True, default='', help_text='Original HTML (for reference)')),
                ('source', models.CharField(choices=[('main', 'Ana Site (acibadem.edu.tr)'), ('bologna', 'Bologna (obs.acibadem.edu.tr)')], default='main', max_length=20)),
                ('category', models.CharField(blank=True, db_index=True, default='', help_text='Page category (e.g., faculty, department, course, admission)', max_length=100)),
                ('language', models.CharField(default='tr', help_text='Content language (tr/en)', max_length=5)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_processed', models.BooleanField(db_index=True, default=False, help_text='Whether chunks and embeddings have been generated')),
            ],
            options={
                'verbose_name': 'Web Page',
                'verbose_name_plural': 'Web Pages',
                'ordering': ['-scraped_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=10)),
                ('content', models.TextField()),
                ('context_used', models.TextField(blank=True, default='', help_text='RAG context that was used to generate this response')),
                ('sources', models.JSONField(blank=True, default=list, help_text='List of source URLs used for the response')),
                ('model_name', models.CharField(blank=True, default='', max_length=100)),
                ('response_time_ms', models.PositiveIntegerField(blank=True, help_text='LLM response time in milliseconds', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.PositiveIntegerField(help_text='Order of chunk within the page')),
                ('content', models.TextField(help_text='Text content of this chunk')),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=768, help_text='nomic-embed-text vector (768 dims)', null=True)),
                ('token_count', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata (section title, headers, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('web_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='chat.webpage')),
            ],
            options={
                'verbose_name': 'Document Chunk',
                'verbose_name_plural': 'Document Chunks',
                'ordering': ['web_page', 'chunk_index'],
                'indexes': [models.Index(fields=['web_page', 'chunk_index'], name='chat_docume_web_pag_a6560c_idx')],
            },
        ),
    ]
