# Generated by Django 5.0.14 on 2026-05-03 18:38

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentchunk",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                blank=True,
                dimensions=1024,
                help_text="bge-m3 vector (1024 dims)",
                null=True,
            ),
        ),
    ]
